name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0/59 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Commiter
        run: |
          git config --local user.email "ld0574@163.com"
          git config --local user.name "ld0574"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "just commit keep office alive"
          git push
